# Generated by Django 3.1.3 on 2020-11-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default=None, max_length=300, null=True)),
                ('name', models.CharField(default=None, max_length=300, null=True)),
                ('address', models.CharField(default=None, max_length=300, null=True)),
                ('space', models.FloatField(default=None, null=True)),
                ('cadastral_number', models.CharField(default=None, max_length=150)),
                ('state_description', models.TextField()),
                ('contact_person', models.CharField(default=None, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('img_url1', models.URLField(blank=True)),
                ('img_url2', models.URLField(blank=True)),
                ('img_url3', models.URLField(blank=True)),
                ('img_url4', models.URLField(blank=True)),
                ('img_url5', models.URLField(blank=True)),
            ],
        ),
    ]
