# Generated by Django 3.1.3 on 2020-11-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0002_property_pretenders_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
