# Generated by Django 3.1.3 on 2020-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0004_auto_20201115_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact_person',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
